In [ ]:
import pandas as _hex_pandas
import datetime as _hex_datetime
import json as _hex_json

In [ ]:
hex_scheduled = _hex_json.loads("false")

In [ ]:
hex_user_email = _hex_json.loads("\"example-user@example.com\"")

In [ ]:
hex_user_attributes = _hex_json.loads("{}")

In [ ]:
hex_run_context = _hex_json.loads("\"logic\"")

In [ ]:
hex_timezone = _hex_json.loads("\"UTC\"")

In [ ]:
hex_project_id = _hex_json.loads("\"f65b8adc-6b18-418d-a7e3-76f5a275e09a\"")

In [ ]:
hex_project_name = _hex_json.loads("\"current Diabetes Model Training\"")

In [ ]:
hex_status = _hex_json.loads("\"\"")

In [ ]:
hex_categories = _hex_json.loads("[]")

In [ ]:
hex_color_palette = _hex_json.loads("[\"#4C78A8\",\"#F58518\",\"#E45756\",\"#72B7B2\",\"#54A24B\",\"#EECA3B\",\"#B279A2\",\"#FF9DA6\",\"#9D755D\",\"#BAB0AC\"]")

In [ ]:
# import jinja2
# raw_query = """
#     select * from "diabetes_dataset_combined2.csv";
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     SELECT
#         "Age",
#         "BMI",
#         "Glucose",
#         "Insulin",
#         "HbA1c_level",
#         "Pregnancies",
#         hypertension,
#         "BloodPressure",
#         "SkinThickness",
#         heart_disease,
#         smoking_history,
#         blood_glucose_level,
#         "DiabetesPedigreeFunction",
#         "Outcome_1"
#     FROM diabetes_dataset_combined_4
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder get smoking history out of category. kept it as one column because there is a hiearchy to the smoking variable
le = LabelEncoder()
diabetes_dataset_combined_2["smoking_history"] = le.fit_transform(
    diabetes_dataset_combined_2["smoking_history"]
)

# Write the updated dataset to a new dataframe
diabetes_dataset_combined_2_encoded = diabetes_dataset_combined_2.copy()

# Write the updated dataset to a CSV file
diabetes_dataset_combined_2_encoded.to_csv("diabetes_data_final_file.csv", index=False)

In [ ]:
import time
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Define the features and target variable
y = diabetes_dataset_combined_2_encoded["Outcome_1"]
X = diabetes_dataset_combined_2_encoded.drop(columns=["Outcome_1"])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create and train the DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
start_time = time.time()

# Make predictions on the test set
predictions = dt.predict(X_test)
end_time = time.time()
runtime = end_time - start_time

# Calculate the accuracy
accuracy = accuracy_score(y_test, predictions)

# Calculate precision and recall
precision = precision_score(y_test, predictions, average="binary")
recall = recall_score(y_test, predictions, average="binary")

# Print test metrics
print(f"Precision: {precision}")
print(f"Accuracy: {accuracy}")
print(f"Recall: {recall}")
# Calculate and print the confusion matrix
cm = confusion_matrix(y_test, predictions)
print(f"Confusion Matrix:\n{cm}")
dataset_size = X_train.shape[0] + X_test.shape[0]
total_nodes = dt.tree_.node_count
leaves = dt.tree_.n_leaves
# Print performance metrics
# Print train metrics
# Calculate train metrics
train_predictions = dt.predict(X_train)
train_accuracy = accuracy_score(y_train, train_predictions)
train_precision = precision_score(y_train, train_predictions, average="binary")
train_recall = recall_score(y_train, train_predictions, average="binary")
train_cm = confusion_matrix(y_train, train_predictions)

# Print train metrics
print(f"Train Accuracy: {train_accuracy}")
print(f"Train Precision: {train_precision}")
print(f"Train Recall: {train_recall}")
print(f"Train Confusion Matrix:\n{train_cm}")

# Print test metrics
print(f"Test Accuracy: {accuracy}")
print(f"Test Precision: {precision}")
print(f"Test Recall: {recall}")
print(f"Test Confusion Matrix:\n{cm}")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Total Nodes: {total_nodes}")
print(f"Total Leaves: {leaves}")

Precision: 0.6379310344827587
Accuracy: 0.7467532467532467
Recall: 0.6727272727272727
Confusion Matrix:
[[78 21]
 [18 37]]
Train Accuracy: 1.0
Train Precision: 1.0
Train Recall: 1.0
Train Confusion Matrix:
[[401   0]
 [  0 213]]
Test Accuracy: 0.7467532467532467
Test Precision: 0.6379310344827587
Test Recall: 0.6727272727272727
Test Confusion Matrix:
[[78 21]
 [18 37]]
Runtime: 0.00 seconds
Total Nodes: 205
Total Leaves: 103


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

X = diabetes_dataset_combined_2_encoded.drop(columns=["Outcome_1"])
y = diabetes_dataset_combined_2_encoded["Outcome_1"]

dt = DecisionTreeClassifier()
scores = cross_val_score(dt, X, y, cv=5)

print("Cross-validation scores:", scores)
print("Mean cross-validation score:", scores.mean())

Cross-validation scores: [0.68181818 0.68181818 0.70779221 0.73856209 0.7124183 ]
Mean cross-validation score: 0.7044817927170868


In [ ]:


from sklearn.inspection import permutation_importance

dt.fit(X, y)


result = permutation_importance(dt, X, y, n_repeats=10, random_state=42, n_jobs=-1)

# Create a DataFrame to display the feature importances
feature_importances = pd.DataFrame(
    {"Feature": X.columns, "Importance": result.importances_mean}
)
feature_importances = feature_importances.sort_values(by="Importance", ascending=False)

feature_importances

Feature 
 Importance 
 
 
 
 
 2 
 Glucose 
 0.302734 
 
 
 1 
 BMI 
 0.219792 
 
 
 0 
 Age 
 0.160547 
 
 
 12 
 DiabetesPedigreeFunction 
 0.145964 
 
 
 5 
 Pregnancies 
 0.100651 
 
 
 7 
 BloodPressure 
 0.070182 
 
 
 11 
 blood_glucose_level 
 0.035547 
 
 
 3 
 Insulin 
 0.035547 
 
 
 4 
 HbA1c_level 
 0.030469 
 
 
 8 
 SkinThickness 
 0.005208 
 
 
 10 
 smoking_history 
 0.002344 
 
 
 6 
 hypertension 
 0.000000 
 
 
 9 
 heart_disease 
 0.000000

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

important_features = feature_importances[feature_importances["Importance"] > 0.01][
    "Feature"
].tolist()
print(important_features)
# Define the target variable 'y' and the features 'X'
y = diabetes_dataset_combined_2_encoded["Outcome_1"]
X = diabetes_dataset_combined_2_encoded[important_features]

# Initialize the DecisionTreeClassifier
dt = DecisionTreeClassifier()

# Perform cross-validation
scores = cross_val_score(dt, X, y, cv=k)

# Print the cross-validation scores
print("Cross-validation scores:", scores)
print("Mean cross-validation score:", scores.mean())

['Glucose', 'BMI', 'Age', 'DiabetesPedigreeFunction', 'Pregnancies', 'BloodPressure', 'blood_glucose_level', 'Insulin', 'HbA1c_level']
Cross-validation scores: [0.74025974 0.64935065 0.73376623 0.70588235 0.69934641]
Mean cross-validation score: 0.7057210763093116


In [ ]:
from sklearn.model_selection import GridSearchCV
import warnings

warnings.filterwarnings("ignore")
#similar to the heart disease grid search. this is what model returned as best params after validation. It originally had multiple paramters.
#I just wanted to double check the cross val scores by running it with the params selected.
param_grid = {
    "criterion": ["gini"],
    "splitter": ["random"],
    "max_depth": [50],
    "min_samples_split": [10],
    "min_samples_leaf": [4],
    "max_features": [None],
}

dt1 = DecisionTreeClassifier()
grid_search = GridSearchCV(
    estimator=dt, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2
)
grid_search.fit(
    diabetes_dataset_combined_2_encoded.drop("Outcome_1", axis=1),
    diabetes_dataset_combined_2_encoded["Outcome_1"],
)
best_params = grid_search.best_params_
best_score = grid_search.best_score_
print(best_params, best_score)
best_params, best_score

Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV] END criterion=gini, max_depth=50, max_features=None, min_samples_leaf=4, min_samples_split=10, splitter=random; total time=   0.0s
[CV] END criterion=gini, max_depth=50, max_features=None, min_samples_leaf=4, min_samples_split=10, splitter=random; total time=   0.0s
[CV] END criterion=gini, max_depth=50, max_features=None, min_samples_leaf=4, min_samples_split=10, splitter=random; total time=   0.0s
[CV] END criterion=gini, max_depth=50, max_features=None, min_samples_leaf=4, min_samples_split=10, splitter=random; total time=   0.0s
[CV] END criterion=gini, max_depth=50, max_features=None, min_samples_leaf=4, min_samples_split=10, splitter=random; total time=   0.0s
{'criterion': 'gini', 'max_depth': 50, 'max_features': None, 'min_samples_leaf': 4, 'min_samples_split': 10, 'splitter': 'random'} 0.6979034037857568


({'criterion': 'gini',
  'max_depth': 50,
  'max_features': None,
  'min_samples_leaf': 4,
  'min_samples_split': 10,
  'splitter': 'random'},
 0.6979034037857568)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
import numpy as np

# Select important features based on threshold
important_features = feature_importances[feature_importances["Importance"] > 0.01][
    "Feature"
]
print(important_features)

y = diabetes_dataset_combined_2_encoded["Outcome_1"]
X = diabetes_dataset_combined_2_encoded[important_features]

dt = DecisionTreeClassifier()
#similar to the heart disease grid search. this is what model returned as best params after validation. It originally had multiple paramters.
#I just wanted to double check the cross val scores by running it with the params selected.
# Define the parameter grid for tuning
param_grid = {
    "criterion": ["gini"],
    "splitter": ["random"],
    "max_depth": [50],
    "min_samples_split": [10],
    "min_samples_leaf": [4],
    "max_features": [None],
}

# Set up GridSearchCV with cross-validation
grid_search = GridSearchCV(
    estimator=dt, param_grid=param_grid, cv=5, scoring="accuracy"
)
grid_search.fit(X, y)

# Display best parameters and cross-validation results
print("Best parameters found:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

2                      Glucose
1                          BMI
0                          Age
12    DiabetesPedigreeFunction
5                  Pregnancies
7                BloodPressure
11         blood_glucose_level
3                      Insulin
4                  HbA1c_level
Name: Feature, dtype: object
Best parameters found: {'criterion': 'gini', 'max_depth': 50, 'max_features': None, 'min_samples_leaf': 4, 'min_samples_split': 10, 'splitter': 'random'}
Best cross-validation score: 0.7435616670910787


In [ ]:
# Import necessary libraries for confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score


from sklearn.metrics import precision_score, accuracy_score


from sklearn.tree import DecisionTreeClassifier
import numpy as np


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
# Select important features based on threshold
important_features = feature_importances[feature_importances["Importance"] > 0.01][
    "Feature"
]


# Initialize the Decision Tree model
dt = DecisionTreeClassifier(
    criterion="gini",
    splitter="random",
    max_depth=50,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features=None,
)


# Fit the model
best_model = dt.fit(X_train, y_train)
# Fit the model on the training data
import time

# Start the timer
start_time = time.time()


# Make predictions on the training set
train_predictions = best_model.predict(X_train)

# Calculate training metrics
train_precision = precision_score(y_train, train_predictions)
train_accuracy = accuracy_score(y_train, train_predictions)
train_recall = recall_score(y_train, train_predictions)
train_cm = confusion_matrix(y_train, train_predictions)

# Print training metrics
print("Training set precision:", train_precision)
print("Training set accuracy:", train_accuracy)
print("Training set recall:", train_recall)
print("Training Confusion Matrix:")
print(train_cm)

# Make predictions on the test set
end_time = time.time()
runtime = end_time - start_time
# Get the total number of nodes and leaves

dataset_size = len(X)

# Print the runtime, total leaves, nodes, and dataset size
print(f"Runtime: {runtime:.2f} seconds")
print(f"Total nodes: {n_nodes}")
print(f"Total leaves: {n_leaves}")
print(f"Dataset size: {dataset_size}")
# Evaluate the model on the test set

# Evaluate the model on the test set
# Calculate confusion matrix
predictions = best_model.predict(X_test)
cm = confusion_matrix(y_test, predictions)
print("Confusion Matrix:")
print(cm)  # Calculate precision and accuracy
precision = precision_score(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)
recall = recall_score(y_test, predictions)

print("Test set precision:", precision)
print("Test set accuracy:", accuracy)
print("Test set recall:", recall)
print("Test Confusion Matrix:")

Training set precision: 0.8011049723756906
Training set accuracy: 0.8306188925081434
Training set recall: 0.6807511737089202
Training Confusion Matrix:
[[365  36]
 [ 68 145]]
Runtime: 0.01 seconds
Total nodes: 203
Total leaves: 102
Dataset size: 768
Confusion Matrix:
[[79 20]
 [19 36]]
Test set precision: 0.6428571428571429
Test set accuracy: 0.7467532467532467
Test set recall: 0.6545454545454545
Test Confusion Matrix:


In [ ]:
from sklearn.metrics import precision_score, recall_score
import time
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define the features and target variable
y = diabetes_dataset_combined_2["Outcome_1"]
X = diabetes_dataset_combined_2.drop(columns=["Outcome_1"])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create and train the RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
# Make predictions on the training set
train_predictions = rf.predict(X_train)
start_time = time.time()


predictions = rf.predict(X_test)
end_time = time.time()
runtime = end_time - start_time
# Calculate training accuracy, precision, and recall
train_accuracy = accuracy_score(y_train, train_predictions)
train_precision = precision_score(
    y_train, train_predictions, average="binary", zero_division=1
)
train_recall = recall_score(
    y_train, train_predictions, average="binary", zero_division=1
)

# Calculate training confusion matrix
train_cm = confusion_matrix(y_train, train_predictions)

# Calculate the accuracy
accuracy = accuracy_score(y_test, predictions)

# Calculate precision and recall
precision = precision_score(y_test, predictions, average="binary", zero_division=1)
recall = recall_score(y_test, predictions, average="binary", zero_division=1)
dataset_size = len(X)
total_nodes = sum(estimator.tree_.node_count for estimator in rf.estimators_)
leaves = sum(estimator.tree_.n_leaves for estimator in rf.estimators_)

# Print precision and recall
print(f"Precision: {precision}")
print(f"Recall: {recall}")
# Calculate and print the confusion matrix
cm = confusion_matrix(y_test, predictions)
print(f"Confusion Matrix:\n{cm}")
print(f"Accuracy: {accuracy}")
print(f"Runtime: {runtime} seconds")
print(f"Total nodes: {total_nodes}")
print(f"Total leaves: {leaves}")
# Print training metrics
print(f"Training Accuracy: {train_accuracy}")
print(f"Training Precision: {train_precision}")
print(f"Training Recall: {train_recall}")
print(f"Training Confusion Matrix:\n{train_cm}")
print(f"Dataset size: {dataset_size}")

Precision: 0.6666666666666666
Recall: 0.6545454545454545
Confusion Matrix:
[[81 18]
 [19 36]]
Accuracy: 0.7597402597402597
Runtime: 0.01489567756652832 seconds
Total nodes: 20364
Total leaves: 10232
Training Accuracy: 1.0
Training Precision: 1.0
Training Recall: 1.0
Training Confusion Matrix:
[[401   0]
 [  0 213]]
Dataset size: 768


In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Use the 'diabetes_dataset_combined_2' dataset and 'heart_disease' as the target variable
X = diabetes_dataset_combined_2.drop(columns=["Outcome_1"])
y = diabetes_dataset_combined_2["Outcome_1"]

# Create a random forest classifier
rf = RandomForestClassifier()

# Fit the model on the training data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit the model on the training data
rf.fit(X_train, y_train)

# Predict on the test data
predictions = rf.predict(X_test)

# Evaluate the model
test_score = rf.score(X_test, y_test)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
# Get feature importances
feature_importances = pd.DataFrame(
    {"Feature": X.columns, "Importance": rf.feature_importances_}
)

# Sort the feature importances in descending order
feature_importances = feature_importances.sort_values(by="Importance", ascending=False)

# Display the feature importances
print(feature_importances)

                     Feature  Importance
2                    Glucose    0.235802
1                        BMI    0.139330
0                        Age    0.124804
12  DiabetesPedigreeFunction    0.097652
7              BloodPressure    0.070883
5                Pregnancies    0.067739
3                    Insulin    0.059501
11       blood_glucose_level    0.057952
8              SkinThickness    0.057472
4                HbA1c_level    0.049703
10           smoking_history    0.027819
6               hypertension    0.007952
9              heart_disease    0.003392


In [ ]:


# Import necessary libraries
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the grid search model
rf = RandomForestClassifier(n_estimators=100, random_state=42)
param_grid = {
    "criterion": ["gini"],
    "max_depth": [6],
    "max_features": ["auto"],
    "n_estimators": [200],
}
grid_search = GridSearchCV(
    estimator=rf, param_grid=param_grid, cv=10, n_jobs=-1, scoring="accuracy"
)


important_features = feature_importances[feature_importances["Importance"] > 0.01][
    "Feature"
].tolist()

# Prepare the data
X = diabetes_dataset_combined_2.drop(columns=["Outcome_1"])
y = diabetes_dataset_combined_2["Outcome_1"]  # Target variable 'Outcome_1'

# Train the model
scores = cross_val_score(rf, X[important_features], y, cv=10)

print(f"Cross-validation scores: {scores}")
print(f"Mean cross-validation score: {scores.mean()}")

# Make predictions
grid_search.fit(X[important_features], y)


rf.fit(X_train[important_features], y_train)  # Train the model on the training set

y_pred = rf.predict(X_test[important_features])

# Print feature importance columns
print(f"Features used in the prediction: {important_features}")
print(f"important_features = {important_features}")

Cross-validation scores: [0.7012987  0.79220779 0.80519481 0.67532468 0.7012987  0.77922078
 0.81818182 0.81818182 0.75       0.80263158]
Mean cross-validation score: 0.7643540669856459
Features used in the prediction: ['Glucose', 'BMI', 'Age', 'DiabetesPedigreeFunction', 'BloodPressure', 'Pregnancies', 'Insulin', 'blood_glucose_level', 'SkinThickness', 'HbA1c_level', 'smoking_history']
important_features = ['Glucose', 'BMI', 'Age', 'DiabetesPedigreeFunction', 'BloodPressure', 'Pregnancies', 'Insulin', 'blood_glucose_level', 'SkinThickness', 'HbA1c_level', 'smoking_history']


In [ ]:
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import time

# Filter features based on importance
selected_features = feature_importances[feature_importances["Importance"] > 0.01][
    "Feature"
].tolist()
X_train, X_test, y_train, y_test = train_test_split(
    X[selected_features], y, test_size=0.2, random_state=42
)
print("Selected Features:", X_train.columns)

param_grid = {
    "criterion": ["gini"],
    "max_depth": [6],
    "max_features": ["auto"],
    "n_estimators": [200],
}

start_time = time.time()
grid_search.fit(X_train, y_train)
end_time = time.time()
runtime = end_time - start_time
best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_
ypred = best_estimator.predict(X_test)
test_accuracy = accuracy_score(y_test, ypred)
cm = confusion_matrix(y_test, ypred)
print(f"Best Parameters: {best_params}")
print(f"Accuracy: {accuracy}")
test_precision = precision_score(y_test, ypred)
test_recall = recall_score(y_test, ypred)
print(f"Test Accuracy: {test_accuracy}")
print(f"Test Precision: {test_precision}")
print(f"Test Recall: {test_recall}")
print(f"Test Confusion Matrix:\n{cm}")
dataset_size = len(X_train) + len(X_test)
train_predictions = best_estimator.predict(X_train)
train_accuracy = accuracy_score(y_train, train_predictions)
train_precision = precision_score(y_train, train_predictions)
train_recall = recall_score(y_train, train_predictions)
train_cm = confusion_matrix(y_train, train_predictions)
print(f"Train Accuracy: {train_accuracy}")
print(f"Train Precision: {train_precision}")
print(f"Train Recall: {train_recall}")
print(f"Train Confusion Matrix:\n{train_cm}")
total_nodes = best_estimator.estimators_[0].tree_.node_count
leaves = best_estimator.estimators_[0].tree_.n_leaves
print(f"Runtime: {runtime} seconds")
print(f"Total Nodes: {total_nodes}")
print(f"Total Leaves: {leaves}")
print(f"Dataset Size: {dataset_size}")

Selected Features: Index(['Glucose', 'BMI', 'Age', 'DiabetesPedigreeFunction', 'BloodPressure',
       'Pregnancies', 'Insulin', 'blood_glucose_level', 'SkinThickness',
       'HbA1c_level', 'smoking_history'],
      dtype='object')
Best Parameters: {'criterion': 'gini', 'max_depth': 6, 'max_features': 'auto', 'n_estimators': 200}
Accuracy: 0.7597402597402597
Test Accuracy: 0.7467532467532467
Test Precision: 0.6481481481481481
Test Recall: 0.6363636363636364
Test Confusion Matrix:
[[80 19]
 [20 35]]
Train Accuracy: 0.9218241042345277
Train Precision: 0.9459459459459459
Train Recall: 0.8215962441314554
Train Confusion Matrix:
[[391  10]
 [ 38 175]]
Runtime: 4.40130877494812 seconds
Total Nodes: 75
Total Leaves: 38
Dataset Size: 768


In [ ]:


import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Import confusion_matrix (already imported in the environment)
# from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay


drop_columns = ["Outcome_1"]
X = diabetes_dataset_combined_2.drop(columns=drop_columns)
y = diabetes_dataset_combined_2["Outcome_1"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Initialize and train the logistic regression model
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = logreg.predict(X_test)

# Calculate accuracy, precision, and recall
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
# Print accuracy, precision, and recall
# Print train metrics
train_predictions = logreg.predict(X_train)
train_accuracy = accuracy_score(y_train, train_predictions)
train_precision = precision_score(y_train, train_predictions)
train_recall = recall_score(y_train, train_predictions)
print(f"Train Accuracy: {train_accuracy:.2f}")
print(f"Train Precision: {train_precision:.2f}")
print(f"Train Recall: {train_recall:.2f}")

# Print test metrics
print(f"Test Accuracy: {accuracy:.2f}")
print(f"Test Precision: {precision:.2f}")
print(f"Test Recall: {recall:.2f}")
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
# Print test metric
print(
    f"Test Metric - Accuracy: {accuracy:.2f}, Precision: {precision:.2f}, Recall: {recall:.2f}"
)

Train Accuracy: 0.77
Train Precision: 0.72
Train Recall: 0.56
Test Accuracy: 0.76
Test Precision: 0.66
Test Recall: 0.67
Confusion Matrix:
[[80 19]
 [18 37]]
Test Metric - Accuracy: 0.76, Precision: 0.66, Recall: 0.67


In [ ]:
from sklearn.inspection import permutation_importance

# Fit the logistic regression model
logreg = LogisticRegression(max_iter=10000)
logreg.fit(X_train, y_train)

# Calculate permutation importance
result = permutation_importance(
    logreg, X_test, y_test, n_repeats=10, random_state=42, n_jobs=-1
)

# Create a DataFrame for permutation importance
feature_importances = pd.DataFrame(
    {"Feature": X_test.columns, "Importance": result.importances_mean}
)

# Sort the DataFrame by importance
feature_importances = feature_importances.sort_values(by="Importance", ascending=False)

feature_importances

# Print all the features considered
print("Features considered:", X_test.columns.tolist())

Features considered: ['Age', 'BMI', 'Glucose', 'Insulin', 'HbA1c_level', 'Pregnancies', 'hypertension', 'BloodPressure', 'SkinThickness', 'heart_disease', 'smoking_history', 'blood_glucose_level', 'DiabetesPedigreeFunction']


In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# Fit the logistic regression model
logreg = LogisticRegression(max_iter=10000)
logreg.fit(X_train, y_train)

# Get feature importance
feature_importance = np.abs(logreg.coef_[0])

# Create a DataFrame for feature importance
feature_importance_df = pd.DataFrame(
    {"Feature": X_train.columns, "Importance": feature_importance}
)
feature_importance_df = feature_importance_df.sort_values(
    by="Importance", ascending=False
)

feature_importance_df

Feature 
 Importance 
 
 
 
 
 12 
 DiabetesPedigreeFunction 
 0.642799 
 
 
 6 
 hypertension 
 0.234787 
 
 
 1 
 BMI 
 0.102141 
 
 
 9 
 heart_disease 
 0.079439 
 
 
 5 
 Pregnancies 
 0.062275 
 
 
 4 
 HbA1c_level 
 0.040482 
 
 
 0 
 Age 
 0.037823 
 
 
 2 
 Glucose 
 0.034204 
 
 
 10 
 smoking_history 
 0.025301 
 
 
 7 
 BloodPressure 
 0.013569 
 
 
 8 
 SkinThickness 
 0.003193 
 
 
 11 
 blood_glucose_level 
 0.002632 
 
 
 3 
 Insulin 
 0.001763

In [ ]:
from sklearn.inspection import permutation_importance

# Fit the logistic regression model
logreg = LogisticRegression(max_iter=10000)
logreg.fit(X_train, y_train)

# Calculate permutation importance
result = permutation_importance(logreg, X_test, y_test, n_repeats=10, random_state=42)

# Create a DataFrame for permutation importance
feature_importances = pd.DataFrame(
    {"Feature": X_test.columns, "Importance": result.importances_mean}
)

# Sort the DataFrame by importance
feature_importances = feature_importances.sort_values(by="Importance", ascending=False)

feature_importances

Feature 
 Importance 
 
 
 
 
 2 
 Glucose 
 0.138961 
 
 
 1 
 BMI 
 0.030519 
 
 
 12 
 DiabetesPedigreeFunction 
 0.029870 
 
 
 11 
 blood_glucose_level 
 0.018182 
 
 
 3 
 Insulin 
 0.017532 
 
 
 7 
 BloodPressure 
 0.008442 
 
 
 10 
 smoking_history 
 0.005844 
 
 
 8 
 SkinThickness 
 0.003247 
 
 
 4 
 HbA1c_level 
 0.002597 
 
 
 9 
 heart_disease 
 0.000000 
 
 
 6 
 hypertension 
 -0.002597 
 
 
 5 
 Pregnancies 
 -0.002597 
 
 
 0 
 Age 
 -0.011039

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# Filter features with importance above 0.01
important_features = feature_importances[feature_importance_df["Importance"] > 0.01][
    "Feature"
].tolist()
X_filtered = X[important_features]

# Initialize Logistic Regression model
logreg = LogisticRegression(max_iter=1000)

# Perform cross-validation
cv_scores = cross_val_score(logreg, X_filtered, y, cv=5)

# Print cross-validation scores
cv_scores

array([0.75324675, 0.74025974, 0.75974026, 0.79738562, 0.75163399])

In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd

# Fit the logistic regression model
logreg = LogisticRegression(max_iter=10000)
logreg.fit(X_train, y_train)

# Get feature importance
feature_importance = np.abs(logreg.coef_[0])

# Create a DataFrame for feature importance
feature_importance_df = pd.DataFrame(
    {"Feature": X_train.columns, "Importance": feature_importance}
)

feature_importance_df = feature_importance_df.sort_values(
    by="Importance", ascending=False
)

feature_importance_df

Feature 
 Importance 
 
 
 
 
 12 
 DiabetesPedigreeFunction 
 0.642799 
 
 
 6 
 hypertension 
 0.234787 
 
 
 1 
 BMI 
 0.102141 
 
 
 9 
 heart_disease 
 0.079439 
 
 
 5 
 Pregnancies 
 0.062275 
 
 
 4 
 HbA1c_level 
 0.040482 
 
 
 0 
 Age 
 0.037823 
 
 
 2 
 Glucose 
 0.034204 
 
 
 10 
 smoking_history 
 0.025301 
 
 
 7 
 BloodPressure 
 0.013569 
 
 
 8 
 SkinThickness 
 0.003193 
 
 
 11 
 blood_glucose_level 
 0.002632 
 
 
 3 
 Insulin 
 0.001763

In [ ]:
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.linear_model import LogisticRegression

# Filter features with different importance thresholds and return the accuracy, precision, and recall for each threshold
important_features = feature_importance_df[feature_importance_df["Importance"] > 0.01][
    "Feature"
].tolist()
X_filtered = X[important_features]

# Define the parameter grid for hyperparameter tuning
param_grid = {
    "C": [0.01, 0.1, 1, 10, 100],
    "max_iter": [100, 200, 300],
    "penalty": ["l1", "l2"],
    "solver": ["liblinear", "saga"],
}

# Initialize the logistic regression model
logreg = LogisticRegression()

# Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=logreg, param_grid=param_grid, cv=5, scoring="accuracy"
)

# Fit the model
grid_search.fit(X_filtered, y)

# Get the best parameters and best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Perform cross-validation
cv_scores = cross_val_score(grid_search.best_estimator_, X_filtered, y, cv=5)
precision_scores = cross_val_score(
    grid_search.best_estimator_, X_filtered, y, cv=5, scoring="precision"
)
recall_scores = cross_val_score(
    grid_search.best_estimator_, X_filtered, y, cv=5, scoring="recall"
)

# Store results
results = {
    0.01: {
        "best_params": best_params,
        "best_score": best_score,
        "cv_scores": cv_scores,
        "precision_scores": precision_scores,
        "recall_scores": recall_scores,
    }
}

# Print results
for threshold, result in results.items():
    print(f"Threshold: {threshold}")
    print("Best parameters:", result["best_params"])
    print("Best score:", result["best_score"])
    print("Cross-validation scores:", result["cv_scores"])
    print("Cross-validation precision scores:", result["precision_scores"])
    print("Cross-validation recall scores:", result["recall_scores"])

Threshold: 0.01
Best parameters: {'C': 1, 'max_iter': 100, 'penalty': 'l2', 'solver': 'liblinear'}
Best score: 0.7682794329853154
Cross-validation scores: [0.75324675 0.74675325 0.76623377 0.81045752 0.76470588]
Cross-validation precision scores: [0.68181818 0.64705882 0.73684211 0.78571429 0.74285714]
Cross-validation recall scores: [0.55555556 0.61111111 0.51851852 0.62264151 0.49056604]


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

threshold = 0.01
important_features = []

# Define the parameters for the logistic regression model
params = {"C": 1, "max_iter": 100, "penalty": "l1", "solver": "liblinear"}

# Initialize the logistic regression model with the defined parameters
logreg = LogisticRegression(**params)

# Dictionary to store results
results = {}

important_features = feature_importance_df[
    feature_importance_df["Importance"] > threshold
]["Feature"].tolist()
print(f"Features used for threshold {threshold}: {important_features}")
X_filtered = X[important_features]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_filtered, y, test_size=0.20, random_state=42
)

# Fit the model
logreg.fit(X_train, y_train)

# Make predictions on the training set
train_predictions = logreg.predict(X_train)

# Calculate training accuracy, precision, and recall
train_accuracy = accuracy_score(y_train, train_predictions)
train_precision = precision_score(y_train, train_predictions)
train_recall = recall_score(y_train, train_predictions)

# Calculate training confusion matrix
train_cm = confusion_matrix(y_train, train_predictions)
print("Training Confusion Matrix:")
print(train_cm)

# Get the best parameters and best score
best_params = params
best_score = logreg.score(X_train, y_train)

# Make predictions on the test set
y_pred = logreg.predict(X_test)

# Calculate accuracy, precision, and recall
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Store results
results[threshold] = {
    "best_params": best_params,
    "best_score": best_score,
    "test_accuracy": accuracy,
    "test_precision": precision,
    "test_recall": recall,
    "train_accuracy": train_accuracy,
    "train_precision": train_precision,
    "train_recall": train_recall,
}

# Print results
for threshold, result in results.items():
    print(f"Threshold: {threshold}")
    print("Best parameters:", result["best_params"])
    print("Best score:", result["best_score"])
    print("Test accuracy:", result["test_accuracy"])
    print("Test precision:", result["test_precision"])
    print("Test recall:", result["test_recall"])
    print("Train accuracy:", result["train_accuracy"])
    print("Train precision:", result["train_precision"])
    print("Train recall:", result["train_recall"])

Features used for threshold 0.01: ['DiabetesPedigreeFunction', 'hypertension', 'BMI', 'heart_disease', 'Pregnancies', 'HbA1c_level', 'Age', 'Glucose', 'smoking_history', 'BloodPressure']
Training Confusion Matrix:
[[350  51]
 [ 93 120]]
Confusion Matrix:
[[80 19]
 [19 36]]
Threshold: 0.01
Best parameters: {'C': 1, 'max_iter': 100, 'penalty': 'l1', 'solver': 'liblinear'}
Best score: 0.7654723127035831
Test accuracy: 0.7532467532467533
Test precision: 0.6545454545454545
Test recall: 0.6545454545454545
Train accuracy: 0.7654723127035831
Train precision: 0.7017543859649122
Train recall: 0.5633802816901409


In [ ]:
from sklearn.linear_model import Perceptron

from sklearn.preprocessing import LabelEncoder


X = diabetes_dataset_combined_2_encoded.drop(columns=["Outcome_1"])
y = diabetes_dataset_combined_2_encoded["Outcome_1"]



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Define the Perceptron model
perceptron = Perceptron()

# Fit the model on the training data
perceptron.fit(X_train, y_train)

# Make predictions on the test data
y_pred = perceptron.predict(X_test)

# Evaluate the model
test_precision = precision_score(y_test, y_pred, average="binary")
test_recall = recall_score(y_test, y_pred, average="binary")

# Print the evaluation metrics
print(f"Test Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Test Precision: {test_precision}")
print(f"Test Recall: {test_recall}")

Test Accuracy: 0.38961038961038963
Test Precision: 0.3691275167785235
Test Recall: 1.0
