In [ ]:
import pandas as _hex_pandas
import datetime as _hex_datetime
import json as _hex_json

In [ ]:
hex_scheduled = _hex_json.loads("false")

In [ ]:
hex_user_email = _hex_json.loads("\"example-user@example.com\"")

In [ ]:
hex_user_attributes = _hex_json.loads("{}")

In [ ]:
hex_run_context = _hex_json.loads("\"logic\"")

In [ ]:
hex_timezone = _hex_json.loads("\"UTC\"")

In [ ]:
hex_project_id = _hex_json.loads("\"5201d03d-79a9-4f43-82b3-8a89c43ad1f3\"")

In [ ]:
hex_project_name = _hex_json.loads("\"Current model training Heart Disease full dataset\"")

In [ ]:
hex_status = _hex_json.loads("\"\"")

In [ ]:
hex_categories = _hex_json.loads("[]")

In [ ]:
hex_color_palette = _hex_json.loads("[\"#4C78A8\",\"#F58518\",\"#E45756\",\"#72B7B2\",\"#54A24B\",\"#EECA3B\",\"#B279A2\",\"#FF9DA6\",\"#9D755D\",\"#BAB0AC\"]")

In [ ]:
# import jinja2
# raw_query = """
#     select * from "heart_diseases.csv";
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:
# import jinja2
# raw_query = """
#     SELECT
#         ca,
#         age,
#         fbs,
#         chol,
#         "CK-MB",
#         exang,
#         thalch,
#         oldpeak,
#         "Troponin",
#         "sex_Male",
#         trestbps,
#         "Heart rate",
#         "sex_Female",
#         slope_flat,
#         "Blood sugar",
#         thal_normal,
#         restecg_normal,
#         cp_asymptomatic,
#         "dataset_Hungary",
#         slope_upsloping,
#         "cp_typical angina",
#         "dataset_Cleveland",
#         slope_downsloping,
#         "thal_fixed defect",
#         "cp_atypical angina",
#         "dataset_VA Long Beach",
#         "restecg_lv hypertrophy",
#         "thal_reversable defect",
#         "Systolic blood pressure",
#         "Diastolic blood pressure",
#         "restecg_st-t abnormality",
#         num
#     FROM heart_diseases_2;
# """
# sql_query = jinja2.Template(raw_query).render(vars())

In [ ]:

import time
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import confusion_matrix
# import time to count runtime of the model
# from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score




start_time = time.time()
X = heart_diseases.drop(columns=["num"])
y = heart_diseases["num"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
train_score = dt.score(X_train, y_train)
test_score = dt.score(X_test, y_test)
runtime = time.time() - start_time

# Calculate precision and recall
precision = precision_score(y_test, dt.predict(X_test), average="weighted")
recall = recall_score(y_test, dt.predict(X_test), average="weighted")

# Print train accuracy, test accuracy, precision, recall, and confusion matrix
print(f"Train accuracy: {train_score}")
print(f"Test accuracy: {test_score}")
print(
    f"Train Precision: {precision_score(y_train, dt.predict(X_train), average='weighted')}"
)
print(f"Train Recall: {recall_score(y_train, dt.predict(X_train), average='weighted')}")
print(f"Test Precision: {precision}")
print(f"Test Recall: {recall}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, dt.predict(X_test))}")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Dataset size: {len(X)}")
print(f"Confusion Matrix (Train):\n{confusion_matrix(y_train, dt.predict(X_train))}")
print(f"Confusion Matrix (Test):\n{confusion_matrix(y_test, dt.predict(X_test))}")
print(f"Number of nodes: {dt.tree_.node_count}")
print(f"Number of leaves: {dt.get_n_leaves()}")

Train accuracy: 1.0
Test accuracy: 0.7166666666666667
Train Precision: 1.0
Train Recall: 1.0
Test Precision: 0.7235863095238095
Test Recall: 0.7166666666666667
Confusion Matrix:
[[25 10]
 [ 7 18]]
Runtime: 0.01 seconds
Dataset size: 299
Confusion Matrix (Train):
[[125   0]
 [  0 114]]
Confusion Matrix (Test):
[[25 10]
 [ 7 18]]
Number of nodes: 77
Number of leaves: 39


In [ ]:
# Fit Decision Tree

from sklearn.inspection import permutation_importance

dt.fit(X, y)

result = permutation_importance(dt, X, y, n_repeats=10, random_state=42, n_jobs=-1)

# Create a DataFrame to display the feature importances
feature_importances = pd.DataFrame(
    {"Feature": X.columns, "Importance": result.importances_mean}
)
feature_importances = feature_importances.sort_values(by="Importance", ascending=False)

feature_importances

Feature 
 Importance 
 
 
 
 
 15 
 thal_normal 
 0.209030 
 
 
 0 
 ca 
 0.172575 
 
 
 17 
 cp_asymptomatic 
 0.152508 
 
 
 1 
 age 
 0.094649 
 
 
 28 
 Systolic blood pressure 
 0.077258 
 
 
 7 
 oldpeak 
 0.071572 
 
 
 10 
 trestbps 
 0.056856 
 
 
 3 
 chol 
 0.055853 
 
 
 14 
 Blood sugar 
 0.043813 
 
 
 29 
 Diastolic blood pressure 
 0.028763 
 
 
 6 
 thalch 
 0.025753 
 
 
 11 
 Heart rate 
 0.021070 
 
 
 9 
 sex_Male 
 0.016388 
 
 
 8 
 Troponin 
 0.012709 
 
 
 4 
 CK-MB 
 0.009030 
 
 
 26 
 restecg_lv hypertrophy 
 0.000000 
 
 
 24 
 cp_atypical angina 
 0.000000 
 
 
 25 
 dataset_VA Long Beach 
 0.000000 
 
 
 2 
 fbs 
 0.000000 
 
 
 27 
 thal_reversable defect 
 0.000000 
 
 
 22 
 slope_downsloping 
 0.000000 
 
 
 23 
 thal_fixed defect 
 0.000000 
 
 
 16 
 restecg_normal 
 0.000000 
 
 
 21 
 dataset_Cleveland 
 0.000000 
 
 
 20 
 cp_typical angina 
 0.000000 
 
 
 19 
 slope_upsloping 
 0.000000 
 
 
 18 
 dataset_Hungary 
 0.000000 
 
 
 13 
 slope_flat 
 0.000000 
 
 
 12 
 sex_Female 
 0.000000 
 
 
 5 
 exang 
 0.000000 
 
 
 30 
 restecg_st-t abnormality 
 0.000000

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

important_features = feature_importances[feature_importances["Importance"] > 0.05][
    "Feature"
].tolist()
print(important_features)
# Define the target variable 'y' and the features 'X'
y = heart_diseases["num"]
X = heart_diseases[important_features]

# Initialize the DecisionTreeClassifier
dt = DecisionTreeClassifier()

# Perform cross-validation
scores = cross_val_score(dt, X, y, cv=5)

# Print the cross-validation scores
print("Cross-validation scores:", scores)
print("Mean cross-validation score:", np.mean(scores))

['thal_normal', 'ca', 'cp_asymptomatic', 'age', 'Systolic blood pressure', 'oldpeak', 'trestbps', 'chol']
Cross-validation scores: [0.7        0.8        0.71666667 0.75       0.74576271]
Mean cross-validation score: 0.7424858757062147


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
import numpy as np

# Select important features based on threshold from the feature importance
important_features = feature_importances[feature_importances["Importance"] > 0.05]["Feature"]
print(important_features)

# Define the target variable 'y' and the features 'X' using the important features
y = heart_diseases["num"]
X = heart_diseases[important_features]


dt = DecisionTreeClassifier()

# Define a parameter grid for tuning
param_grid = {
    "criterion": ["gini", "entropy"],
    "splitter": ["best", "random"],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [None, "sqrt", "log2"],
}

# Set up GridSearchCV with cross-validation
grid_search = GridSearchCV(estimator=dt, param_grid=param_grid, cv=5, scoring="accuracy")
grid_search.fit(X, y)

# Display the best parameters and cross-validation results
print("Best parameters found:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)


15                thal_normal
0                          ca
17            cp_asymptomatic
1                         age
28    Systolic blood pressure
7                     oldpeak
10                   trestbps
3                        chol
Name: Feature, dtype: object
Best parameters found: {'criterion': 'entropy', 'max_depth': 20, 'max_features': None, 'min_samples_leaf': 2, 'min_samples_split': 10, 'splitter': 'random'}
Best cross-validation score: 0.832598870056497


In [ ]:
import numpy as np
import numpy as np

# Calculate and print precision, accuracy, and recall for test and train
# Compare train metrics to test metrics
import time
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, accuracy_score, recall_score
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

important_features = feature_importances[feature_importances["Importance"] > 0.05][
    "Feature"
]
print("Selected important features:", list(important_features))
print("Selected important features:", important_features)
# Define the target variable 'y' and the features 'X'
y = heart_diseases["num"]
X = heart_diseases[important_features]
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)
# create empty list to then append to. Then take the mean from these lists to get the average score

train_precision_scores = []
train_recall_scores = []
train_accuracy_scores = []
test_precision_scores = []
test_recall_scores = []
test_accuracy_scores = []
#run the model 100 times and get 
for _ in range(100):
    start_time = time.time()
    # Initialize the DecisionTreeClassifier with the specified configuration
    dt = DecisionTreeClassifier(
        criterion="entropy",
        splitter="random",
        max_depth=20,
        min_samples_split=10,
        min_samples_leaf=4,
        max_features=None,
    )
    # Train the model
    dt.fit(X_train, y_train)
    # Make predictions
    y_pred = dt.predict(X_test)
    # Make predictions on the training set
    y_train_pred = dt.predict(X_train)
    # Calculate and print precision, accuracy, and recall
    train_precision = precision_score(y_train, y_train_pred)
    train_recall = recall_score(y_train, y_train_pred)
    train_accuracy = accuracy_score(y_train, y_train_pred)

    # Calculate precision, recall, and accuracy for the test set
    test_precision = precision_score(y_test, y_pred)
    test_recall = recall_score(y_test, y_pred)
    test_accuracy = accuracy_score(y_test, y_pred)

    # Accumulate scores for averaging
    train_precision_scores.append(train_precision)
    train_recall_scores.append(train_recall)
    train_accuracy_scores.append(train_accuracy)
    test_precision_scores.append(test_precision)
    test_recall_scores.append(test_recall)
    test_accuracy_scores.append(test_accuracy)

#take the average of the list and print those score
print(f"Average Train Precision: {np.mean(train_precision_scores):.2f}")
print(f"Average Train Recall: {np.mean(train_recall_scores):.2f}")
print(f"Average Train Accuracy: {np.mean(train_accuracy_scores):.2f}")
print(f"Average Test Precision: {np.mean(test_precision_scores):.2f}")
print(f"Average Test Recall: {np.mean(test_recall_scores):.2f}")
print(f"Average Test Accuracy: {np.mean(test_accuracy_scores):.2f}")

Selected important features: ['thal_normal', 'ca', 'cp_asymptomatic', 'age', 'Systolic blood pressure', 'oldpeak', 'trestbps', 'chol']
Selected important features: 15                thal_normal
0                          ca
17            cp_asymptomatic
1                         age
28    Systolic blood pressure
7                     oldpeak
10                   trestbps
3                        chol
Name: Feature, dtype: object
Average Train Precision: 0.87
Average Train Recall: 0.81
Average Train Accuracy: 0.85
Average Test Precision: 0.80
Average Test Recall: 0.75
Average Test Accuracy: 0.81


In [ ]:
#reimport libraries just in case
import time
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define the features and target variable
y = heart_diseases["num"]
X = heart_diseases.drop(columns=["num"])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create and train the RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
start_time = time.time()
rf.fit(X_train, y_train)
runtime = time.time() - start_time

# Make predictions on the test set
predictions = rf.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, predictions)

# Calculate precision and recall
precision = precision_score(y_test, predictions, average="binary")
recall = recall_score(y_test, predictions, average="binary")

# Calculate train and test scores
train_score = rf.score(X_train, y_train)
test_score = rf.score(X_test, y_test)

# Calculate the number of nodes and leaves in the forest
n_nodes = rf.n_estimators
n_nodes = sum(estimator.tree_.node_count for estimator in rf.estimators_)
dataset_size = X_train.shape[0] + X_test.shape[0]

# Print performance metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
cm = confusion_matrix(y_test, predictions)
print(f"Confusion Matrix:\n{cm}")
print(f"Dataset Size: {dataset_size}")
print(f"Number of Nodes: {n_nodes}")
print(f"Runtime: {runtime:.2f} seconds")

# Compare train metrics to test metrics
print(f"Train Accuracy: {train_score}")
print(f"Test Accuracy: {test_score}")
print(
    f"Train Precision: {precision_score(y_train, rf.predict(X_train), average='binary')}"
)
print(f"Test Precision: {precision}")
print(f"Train Recall: {recall_score(y_train, rf.predict(X_train), average='binary')}")
print(f"Test Recall: {recall}")


# Print total number of nodes and leaves
print(f"Total Number of Nodes: {n_nodes}")
print(f"Total Number of Leaves: {n_leaves}")
print(f"Number of Root Nodes: {n_root_nodes}")

Accuracy: 0.9
Precision: 0.9130434782608695
Recall: 0.84
Confusion Matrix:
[[33  2]
 [ 4 21]]
Dataset Size: 299
Number of Nodes: 7956
Runtime: 0.18 seconds
Train Accuracy: 1.0
Test Accuracy: 0.9
Train Precision: 1.0
Test Precision: 0.9130434782608695
Train Recall: 1.0
Test Recall: 0.84
Total Number of Nodes: 7956
Total Number of Leaves: 6633
Number of Root Nodes: 200


In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score
from sklearn.inspection import permutation_importance

#define varibales and target
X = heart_diseases.drop(columns=["num"])
y = heart_diseases["num"]

# Create a random forest classifier
rf = RandomForestClassifier()

# Fit the model on the training data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit the model on the training data
rf.fit(X_train, y_train)

# Predict on the test data
predictions = rf.predict(X_test)

# Evaluate the model
test_score = rf.score(X_test, y_test)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)

# Get permutation importances
result = permutation_importance(rf, X_test, y_test, n_repeats=10, random_state=42)
feature_importances = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance": result.importances_mean / result.importances_mean.sum(),
    }
)

# Sort the feature importances in descending order
feature_importances = feature_importances.sort_values(by="Importance", ascending=False)

# Display the feature importances
print(feature_importances.reset_index(drop=True))

                     Feature  Importance
0            cp_asymptomatic    0.209877
1                         ca    0.172840
2                    oldpeak    0.135802
3    Systolic blood pressure    0.123457
4                thal_normal    0.111111
5     thal_reversable defect    0.074074
6                     thalch    0.074074
7                        age    0.061728
8                 slope_flat    0.049383
9   Diastolic blood pressure    0.049383
10           slope_upsloping    0.049383
11                  trestbps    0.024691
12               Blood sugar    0.024691
13                     CK-MB    0.024691
14                  Troponin    0.012346
15     dataset_VA Long Beach    0.000000
16        cp_atypical angina    0.000000
17           dataset_Hungary    0.000000
18    restecg_lv hypertrophy    0.000000
19         slope_downsloping    0.000000
20                       fbs    0.000000
21         thal_fixed defect    0.000000
22  restecg_st-t abnormality    0.000000
23         datas

In [ ]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Import necessary libraries

# Define the parameter grid for GridSearchCV. As a note to the professors. There is only one hyper param because I was checking the validation accuracy. 
#This is what the model chose as the best hyper params
#after running the grid search on a few different hyper params
param_grid = {
    "criterion": ["gini"],
    "max_depth": [6],
    "max_features": ["auto"],
    "n_estimators": [200],
}
# Define the grid search model
grid_search = GridSearchCV(
    estimator=rf, param_grid=param_grid, cv=10, n_jobs=-1, scoring="accuracy"
)
important_features = feature_importances[feature_importances["Importance"] > 0.05][
    "Feature"
].tolist()

# Prepare the data
X = heart_diseases.drop(
    columns=["num"]
)  # Drop columns 'num' and 'id' from the dataset
y = heart_diseases["num"]  # Target variable 'num'

# Create the model
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
scores = cross_val_score(rf, X[important_features], y, cv=10)

print(f"Cross-validation scores: {scores}")
print(f"Mean cross-validation score: {scores.mean()}")
grid_search.fit(X_train[important_features], y_train)

# Train the model on the training set
rf.fit(X_train[important_features], y_train)

# Make predictions on the test set
y_pred = rf.predict(X_test[important_features])
# Print feature importance columns
print(f"Features used in the prediction: {important_features}")
print(f"important_features = {important_features}")

Cross-validation scores: [0.9        0.83333333 0.9        0.9        0.8        0.66666667
 0.7        0.8        0.73333333 0.93103448]
Mean cross-validation score: 0.8164367816091953
/home/hexuser/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.9/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/home/hexuser/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.9/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  wa

In [ ]:
import time
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Example data setup (replace with your data)
# X, y = <your_features>, <your_labels>
# feature_importances = <your_feature_importances_dataframe>

start_time = time.time()

# Filter features based on importance
selected_features = feature_importances[feature_importances["Importance"] > 0.05][
    "Feature"
].tolist()
X_train, X_test, y_train, y_test = train_test_split(
    X[selected_features], y, test_size=0.2, random_state=42
)
print("Selected Features:", X_train.columns)

# Define the parameter grid for GridSearchCV
param_grid = {
    "criterion": ["gini"],
    "max_depth": [6],
    "max_features": ["auto"],
    "n_estimators": [200],
}


# Evaluate on the test set
# Fit the RandomForestClassifier
rf = RandomForestClassifier(**best_params)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
runtime = time.time() - start_time
test_accuracy = accuracy_score(y_test, y_pred)
test_precision = precision_score(y_test, y_pred)
test_recall = recall_score(y_test, y_pred)
test_conf_matrix = confusion_matrix(y_test, y_pred)

# Evaluate on the training set
y_train_pred = rf.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred)
train_recall = recall_score(y_train, y_train_pred)
train_conf_matrix = confusion_matrix(y_train, y_train_pred)

# Print performance metrics
print(f"Test Accuracy: {test_accuracy}")
print(f"Test Precision: {test_precision}")
print(f"Test Recall: {test_recall}")
print(f"Test Confusion Matrix:\n{test_conf_matrix}")
print(f"Train Accuracy: {train_accuracy}")
print(
    f"Train Precision: {precision_score(y_train, rf.predict(X_train), average='binary')}"
)
print(f"Train Recall: {train_recall}")
print(f"Train Confusion Matrix:\n{train_conf_matrix}")
print(f"Runtime: {runtime:.2f} seconds")

# Calculate total number of nodes, leaves, and root nodes
n_nodes = 0
n_leaves = 0
n_root_nodes = len(rf.estimators_)  # Each tree has one root node

for tree in rf.estimators_:
    n_nodes += tree.tree_.node_count  # Total nodes in the tree
    n_leaves += tree.tree_.n_leaves  # Total leaves in the tree

# Print total number of nodes and leaves
print(f"Total Number of Nodes: {n_nodes}")
print(f"Total Number of Leaves: {n_leaves}")
print(f"Number of Root Nodes: {n_root_nodes}")

Selected Features: Index(['cp_asymptomatic', 'ca', 'oldpeak', 'Systolic blood pressure',
       'thal_normal', 'thal_reversable defect', 'thalch', 'age'],
      dtype='object')
/home/hexuser/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.9/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
Test Accuracy: 0.9
Test Precision: 0.9130434782608695
Test Recall: 0.84
Test Confusion Matrix:
[[33  2]
 [ 4 21]]
Train Accuracy: 0.9497907949790795
Train Precision: 0.9811320754716981
Train Recall: 0.9122807017543859
Train Confusion Matrix:
[[123   2]
 [ 10 104]]
Runtime: 0.36 seconds
Total Number of Nodes: 12064
Total Number of Leaves: 6132
Number of Root Nodes: 200


In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, precision_score, recall_score

X = heart_diseases_2.drop(columns=["num"])
y = heart_diseases_2["num"]
# Create Perceptron model
perceptron = Perceptron()

# Train the model
perceptron.fit(X_train, y_train)

# Make predictions
y_train_pred = perceptron.predict(X_train)
y_test_pred = perceptron.predict(X_test)

# Evaluate the model
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
train_precision = precision_score(y_train, y_train_pred)
test_precision = precision_score(y_test, y_test_pred)
train_recall = recall_score(y_train, y_train_pred)
test_recall = recall_score(y_test, y_test_pred)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Train Precision:", train_precision)
print("Test Precision:", test_precision)
print("Train Recall:", train_recall)
print("Test Recall:", test_recall)

Train Accuracy: 0.5271966527196653
Test Accuracy: 0.6
Train Precision: 1.0
Test Precision: 1.0
Train Recall: 0.008771929824561403
Test Recall: 0.04
